### ISSUE TITLE
 Localization is needed

### ISSUE THREAD

**Issue by lewadedun** [tworaz/sailfish-ytplayer#12]
Can you start using the Transifex?

**Comment by tworaz** [comment]
Currently no. I have a plan to put some more effort into YTPlayer translation for 0.5.0 release, which should happen roughly 2-3 months from now.

**Comment by Thaodan** [comment]
Added a German Translation, translate cache settings.
https://github.com/tworaz/sailfish-ytplayer/pull/16

**Comment by tworaz** [comment]
From 0.5.0 localizations will be officially supported. If you'd like to contribute support for your own native language you can do so via project Transifex page: https://www.transifex.com/tworaz/ytplayer. Closing.
