### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Vistaus** [tworaz/sailfish-ytplayer#18]
Hello,

first of all: thank you so much for this great app! Been using it for the last couple of months and it's a great YouTube player! You're doing a splendid job on bringing us sailors a native YouTube app :)

I've created a Dutch translation: https://www.dropbox.com/s/169n6fzye7hj2gx/nl.ts?dl=0
Btw, maybe you could set up a Transifex account for YTPlayer translations?

**Comment by tworaz** [comment]
I'm glad you like YTPlayer. It's nice to know people are using my code :)

Thanks for the translation. I'll try to include it in next 0.4.x release. I'll also push it to master, but it'll probably quickly become incomplete.

As for the transifex I actually do plan to put some extra effort into translations for 0.5.0 release. Right now YTPlayer does contain the necessary code for using qt translation files, but I'd like to add some extra stuff before I ask people to translate it. First I'd like to 

1. Have a place in About page where translation credits can be displayed.
2. Have an option in settings to use a different language for YTPlayer than the system one. The default would be to fallback to system locale, but if the user wants to use a different translation it should also be possible.

After those features are present I'll officially start looking for translators.

**Comment by tworaz** [comment]
Merged to master so closing,
