### ISSUE TITLE
Easier way to repeat searches

### ISSUE THREAD

**Issue by smyru** [tworaz/sailfish-ytplayer#23]
Here is a feature request of kid mode sort. The use case is that some users repeat the same searches over and over again, it would be nice to either have previous searches below input on search page, or a way to save selected search. I guess the former would be simpler.

**Comment by tworaz** [comment]
Not sure this is what you have in mind, but for 0.5.0 I've implemented support for search suggestions, see fc2e6c44f3e22747c620684e74feeb9a1288d03a. Basically you can either use google or your local search history to provide search query suggestions. Should make searching much simpler.
