### ISSUE TITLE
Video Quality selection menu navigation gesture clashes with Events view menu & video slider

### ISSUE THREAD

**Issue by BegoneRaven** [tworaz/sailfish-ytplayer#27]
Version:0.4.3-c8d2db8
Due to internet connection quality issues, I often try to choose 360p...
But navigating to the selection menu appears is a bit tricky..
If we touch too low, the the Events view menu would pop up.
If we touch at the progress slider, then, it kind of works, but many times, I end up moving the slider forward or backward .. causing unncessary buffering & losing track of what is being watched!

**Comment by tworaz** [comment]
I do plan to work on video player page for 0.6.0 release. This is actually one of the issues I'd like to solve somehow. No idea how, yet.

**Comment by tworaz** [comment]
Already fixed on master. Will be released in 0.5.0.
