### ISSUE TITLE
When paused in landcape mode, the title & duration slider remain forever on screen obstructing the video

### ISSUE THREAD

**Issue by BegoneRaven** [tworaz/sailfish-ytplayer#28]
Version:0.4.3-c8d2db8
When paused, it would be nice if the title, duration slider & play/pause button etc, would fade out(just like when playing)... 
This would help in watching (or better reading) videos that have text at the botton of the video.
Let the sliders come back.. may be.. after a single tap

**Comment by tworaz** [comment]
Hmm, interesting use case. I admit I've never thought about that. My guess this is an issue when viewing the video in landscape mode. I should be able to squeeze this feature for 0.5.x. It does not sound too complicated.

**Comment by tworaz** [comment]
Just noticed something I completely forgot about. You can actually hide video controls when playback is paused in landscape mode. You just need to manually perform down swipe gesture on the bottom bar.

**Comment by BegoneRaven** [comment]
Thanks for letting me know that.. :)
Hmmm... its almost an edge-start edge-end short distance swipe.....
IMHO swipes should have some distance coverage for an ergonomically satisfactory swipe.. :)

**Comment by tworaz** [comment]
Already fixed on master and will be released in 0.5.0. Closing.
