### ISSUE TITLE
Video Quality always defaults to 720p. Can we have global settings ?

### ISSUE THREAD

**Issue by BegoneRaven** [tworaz/sailfish-ytplayer#29]
Even though 360p is set once during a playback session, after the next consecutive search & play procedure, the default video resolution choice ends up being 720p.
As of now it looks like the setting is momentary for a particular video playback session.
May be some global settings can be added (for eg: Settings\Playback), to set the default quality to attempt playing (as in Settings\Download)

..Keep up the good work :)

**Comment by tworaz** [comment]
Already implemented on master. Will be released in 0.5.0. Closing as fixed.
