### ISSUE TITLE
Account integration gets stuck in Signing In.

### ISSUE THREAD

**Issue by ApostolosB** [tworaz/sailfish-ytplayer#36]
As the title suggests. Upon taping the account integration setting it just shows the spinning animation and the only thing you can do is go back.

![20150917201408](https://cloud.githubusercontent.com/assets/13685565/9940576/5d4a5d1a-5d79-11e5-9ea2-06c03bd5033d.jpg)

**Comment by tworaz** [comment]
Hmm, it seems SilicaWebView component has managed to load some content, but it never sent any notifications about finishing loading the content. The page basically waits to show the sign-in page after it has been fully loaded. Do you have access to a terminal app? It will be installed automatically after you enable developer mode.

In the terminal app try to execute the following command:
 rm -rf /home/nemo/.local/share/harbour-ytplayer/harbour-ytplayer/.QtWebKit/

This should remove local QtWebKit private data used by the engine instance embedded in YTPlayer. If this doesn't help we'll probably need a debug builds with some extra logs.

**Comment by tworaz** [comment]
On a side note, it seems your device does not have python installed by default. Could you check if by chance there is /usr/bin/python2 or /usr/bin/python3 binary present? YTPlayer needs python to run youtube-dl in order to find direct streams for copyrighted content. Unfortunately harbour apps are not allowed to depend on python so I simply omit that dependency. So far every device I had access to came with it installed so it did not seem to be a problem. In your case however it seems python is missing.

**Comment by ApostolosB** [comment]
Python3 is intalled. At least there is a python3 file in /usr/bin. I don't have dev mode enabled -and don't want to enable it cause i'll start messing with it- but i removed it (.QtWebKit) with the File Browser app and it still gets stuck. The logs display exactly the same as the first message.

Leave the bug open. Someone else might be more helpfull than me.

**Comment by tworaz** [comment]
Well, if you still would like to help could you try this build: http://tworaz.net/downloads/jolla/YTPlayer/debug/harbour-ytplayer-0.5.0-1.armv7hl.rpm? It should expose the web view element as soon as it gets non empty title from the view. It also contains some extra logging.

**Comment by tworaz** [comment]
Version 0.5.1 contains a potential workaround for the problem. If possible please check if it solves the problem you were facing.

**Comment by ApostolosB** [comment]
Didn't test extensively but it showed the login page. So i am closing this.

Thanks for your work.
