### ISSUE TITLE
Playback of many videos doesn't work

### ISSUE THREAD

**Issue by KingDuckZ** [tworaz/sailfish-ytplayer#37]
Many videos won't allow playback/download. The app just shows a message like "YTPlayer failed to find usable video streams".
As an example try searching for "Discovery Channel - Large Asteroid Impact Simulation" in the app. Pick the first result. No playback is possible. Many other videos have the same problem.

Just trying some random videos, I can find plenty that won't work:
* Love and Trolls - Boxxy
* Brann - JOA (God Yu Tekem Laef Blong Mi) (Preview)
* Soprano - Clown [Clip Officiel]
* [60fps] Sweet Magic スイートマジック - Kagamine Rin 鏡音リン Project DIVA English Romaji PDA FT
* Guè Pequeno - Il Drink & La Jolla ft. Ntò
* Monster Hunter Freedom Unite : Epic Moments (Longsword, Hammer, Great Sword and Bow) ~Ultimate Art 
* AGK Ep 31 Angry German Kid Gets a Girlfriend
* Rammstein - Sonne (HD)
* Lonelygirl15- Music Video Parody- Daniel's Song
* Maurizio - Cinque minuti e poi

**Comment by tworaz** [comment]
Most of those videos look like copyrighted material. This means YTPlayer will fall back to youtube-dl to find the actual video streams. Now, youtube-dl is a python script and apparently python 2.7 may not be installed on some devices by default. Could you check if you get similar warning message to the one visible in https://github.com/tworaz/sailfish-ytplayer/issues/36? If so please check if you have at least /usr/bin/python3 binary present. If you have one I believe the debug builds from the same ticket should work for you. I plan to switch to python3 for 0.5.1.

**Comment by gitarra** [comment]
I have the same issue. I get the python youtube-dl youtune-dl no streams found error messages and cannot watch videos.

I dont have usr/bin/python3 on my device. I am running 1.1.9.

**Comment by tworaz** [comment]
Well for current stable release python2 is actually used. Now if python3 is also not present, I'll need to figure out alternative solution to the streams problem. Unfortunately harbour apps can't depend on any python version. The hard part is I don't really have the time to re-implement the functionality youtube-dl is providing in C++. Last time I've analysed this it'd take at least 100 man hours to get this done. And this is just the initial implementation. After that I'd also need to maintain it and adjust the code to any changes done server side.

**Comment by gitarra** [comment]
I have had this issue as long as I can remember. Recently did a factory reset as well, never had python installed on my device.

**Comment by tworaz** [comment]
Version 0.5.1 should contain a potential workaround for the problem, please let me know if it works for you.

**Comment by gitarra** [comment]
Works for me.  :+1: 

Can watch these videos now.
