### ISSUE TITLE
i486 build to Jolla Harhour

### ISSUE THREAD

**Issue by Termitebug** [tworaz/sailfish-ytplayer#47]
Hi, I have built a YTPlayer github clone to a real hardware, Jolla Tablet with SF SDK, and it works&playbacks fine without any code change. Except the connection type changer in QML pages which can be commented out to hide the _cellural_ options.
I would like to see Tablet version of YPT in Jolla Harbour.

**Comment by direc85** [comment]
I think I can make it happen. After that, we'll have one more version of of YTPlayer, but because youtube-dl  needs (regular?) updating as well, it has to be done.

**Comment by direc85** [comment]
There is now i486 build in GitHub and OpenRepos, too. You can use Storeman to download it.

It's not yet in Harbour, though, but will be eventually.
